import type {
  DirectiveCategory,
  InstructionFileType,
  NormalizedDirective,
  NormalizedInstructionFile
} from "@directiveops/constitution-model";

export interface TranslateOptions {
  /** Add a credit header comment. Default: true */
  creditHeader?: boolean;
}

const CREDIT_HEADER = "# Generated by DirectiveOps — https://directiveops.dev\n\n";

/**
 * Translate a parsed instruction file into the target format.
 * Self-translation (same source and target type) returns the original content unchanged.
 */
export function translateFile(
  source: NormalizedInstructionFile,
  targetType: InstructionFileType,
  options?: TranslateOptions
): string {
  if (source.fileType === targetType) {
    return source.rawContent;
  }

  const credit = options?.creditHeader !== false ? CREDIT_HEADER : "";

  switch (targetType) {
    case "AGENTS_MD":
      return credit + serializeAgentsMd(source);
    case "CLAUDE_MD":
      return credit + serializeClaudeMd(source);
    case "CURSOR_RULES":
      return credit + serializeCursorRules(source);
    case "COPILOT_INSTRUCTIONS":
      return credit + serializeCopilotInstructions(source);
    case "GITHUB_INSTRUCTIONS":
      return credit + serializeGithubInstructions(source);
    case "GEMINI_MD":
      return credit + serializeGeminiMd(source);
    case "WINDSURF_INSTRUCTIONS":
      return credit + serializeWindsurfInstructions(source);
    case "COPILOT_CONFIG":
      return credit + serializeCopilotConfig(source);
    default:
      throw new UnsupportedTranslationTargetError(targetType);
  }
}

export class UnsupportedTranslationTargetError extends Error {
  constructor(public readonly targetType: string) {
    super(`Unsupported translation target: ${targetType}`);
    this.name = "UnsupportedTranslationTargetError";
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function groupDirectivesByCategory(
  directives: NormalizedDirective[]
): Map<DirectiveCategory, NormalizedDirective[]> {
  const grouped = new Map<DirectiveCategory, NormalizedDirective[]>();
  for (const directive of directives) {
    const category = directive.category;
    const existing = grouped.get(category);
    if (existing) {
      existing.push(directive);
    } else {
      grouped.set(category, [directive]);
    }
  }
  return grouped;
}

const CATEGORY_ORDER: DirectiveCategory[] = [
  "testing",
  "security",
  "workflow",
  "style",
  "repo-conventions",
  "documentation",
  "release",
  "ownership",
  "quality",
  "unknown"
];

function categoryToHeading(category: DirectiveCategory): string {
  switch (category) {
    case "repo-conventions":
      return "Repo Conventions";
    case "unknown":
      return "General";
    default:
      return category.charAt(0).toUpperCase() + category.slice(1);
  }
}

function directiveText(directive: NormalizedDirective): string {
  return directive.rawText.trim() || directive.normalizedText.trim();
}

function renderCategorySections(
  directives: NormalizedDirective[],
  headingPrefix: string
): string {
  const grouped = groupDirectivesByCategory(directives);
  const sections: string[] = [];

  for (const category of CATEGORY_ORDER) {
    const items = grouped.get(category);
    if (!items || items.length === 0) continue;

    sections.push(`${headingPrefix} ${categoryToHeading(category)}`);
    for (const directive of items) {
      sections.push(`- ${directiveText(directive)}`);
    }
    sections.push("");
  }

  return sections.join("\n");
}

// ---------------------------------------------------------------------------
// Format serializers
// ---------------------------------------------------------------------------

function serializeAgentsMd(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  // Title
  lines.push(`# ${source.path.replace(/\\/g, "/").split("/").pop() ?? "Instructions"}`);
  lines.push("");

  // Metadata block
  if (source.scope && source.scope !== "unknown") {
    lines.push(`Scope: ${source.scope}`);
  }
  if (source.owners.length > 0) {
    lines.push(`Owners: ${source.owners.map((o) => o.owner).join(", ")}`);
  }
  if (source.imports.length > 0) {
    lines.push(`Imports: ${source.imports.map((i) => i.target).join(", ")}`);
  }
  if (source.scope !== "unknown" || source.owners.length > 0 || source.imports.length > 0) {
    lines.push("");
  }

  // Directives grouped by category
  lines.push(renderCategorySections(source.directives, "##"));

  return lines.join("\n").trimEnd() + "\n";
}

function serializeClaudeMd(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  lines.push(`# CLAUDE.md`);
  lines.push("");
  lines.push(renderCategorySections(source.directives, "##"));

  return lines.join("\n").trimEnd() + "\n";
}

function serializeCursorRules(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  const grouped = groupDirectivesByCategory(source.directives);

  for (const category of CATEGORY_ORDER) {
    const items = grouped.get(category);
    if (!items || items.length === 0) continue;

    lines.push(`# ${categoryToHeading(category)}`);
    lines.push("");
    for (const directive of items) {
      lines.push(directiveText(directive));
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

function serializeCopilotInstructions(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  lines.push(`# Copilot Instructions`);
  lines.push("");
  lines.push(renderCategorySections(source.directives, "##"));

  return lines.join("\n").trimEnd() + "\n";
}

function serializeGithubInstructions(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  lines.push(`# GitHub Instructions`);
  lines.push("");
  lines.push(renderCategorySections(source.directives, "##"));

  return lines.join("\n").trimEnd() + "\n";
}

function serializeGeminiMd(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  lines.push(`# GEMINI.md`);
  lines.push("");
  lines.push(renderCategorySections(source.directives, "##"));

  return lines.join("\n").trimEnd() + "\n";
}

function serializeWindsurfInstructions(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  const grouped = groupDirectivesByCategory(source.directives);

  for (const category of CATEGORY_ORDER) {
    const items = grouped.get(category);
    if (!items || items.length === 0) continue;

    lines.push(`# ${categoryToHeading(category)}`);
    lines.push("");
    for (const directive of items) {
      lines.push(`- ${directiveText(directive)}`);
    }
    lines.push("");
  }

  return lines.join("\n").trimEnd() + "\n";
}

function serializeCopilotConfig(source: NormalizedInstructionFile): string {
  const lines: string[] = [];

  lines.push("# Copilot configuration");
  lines.push("# Generated by DirectiveOps");
  lines.push("");
  lines.push("instructions:");

  const grouped = groupDirectivesByCategory(source.directives);

  for (const category of CATEGORY_ORDER) {
    const items = grouped.get(category);
    if (!items || items.length === 0) continue;

    lines.push(`  # ${categoryToHeading(category)}`);
    for (const directive of items) {
      const text = directiveText(directive).replace(/"/g, '\\"');
      lines.push(`  - "${text}"`);
    }
  }

  lines.push("");
  return lines.join("\n");
}
